# Generated by Django 4.2.5 on 2023-09-18 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_alumni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='student_number',
            new_name='alumni_number',
        ),
    ]
